### ISSUE TITLE
Move away from hardcoded numbers for ladders/modules

### ISSUE THREAD

**Issue by tvami** [CMSTrackerDPG/SiPixelTools-LA-Calibration#5]
The number of modules/ladders is hardcoded in the code, see
https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration/blob/master/src/SiPixelLorentzAngle.cc#L141

However this does change between Phase-1 and Phase-2, so the code is not directly transferable. 

Marco created a PR that introduces the PixelTopologyMap which could be used to get rid of this, see
 https://github.com/cms-sw/cmssw/pull/33319

With this one can take the info from the EventSetup, something like this:
```
 // get the Tracker geometry from event setup
const TrackerGeometry* trackerGeometry_ = &iSetup.getData(geomEsToken_);
const TrackerTopology* tTopo_ = &iSetup.getData(topoToken_);

PixelTopologyMap map(trackerGeometry_,tTopo_);
const auto nLadders_L1 = map.getLadders(1);
const auto nModules_l1 = map.getModules(1);
```
+ the same has to be done for the endcaps

However the EventSetup is not available at the beginJob() so one needs to move the histogram booking to beginRun() and check if it was already done once.

This is not urgent, maybe when @wweiphy comes back to this project she could take it, or when @tsusa submits a bigger production for the UL trends

**Comment by mmusich** [comment]
Can this be closed?
