### ISSUE TITLE
Compilation issue in 11_3_X

### ISSUE THREAD

**Issue by tvami** [CMSTrackerDPG/SiPixelTools-LA-Calibration#7]
I'd like to create LA trees for CRUZET, so I have to use 11_3_X.

Doing
```
cmsrel CMSSW_11_3_4_patch1
cd CMSSW_11_3_4_patch1/src/
cmsenv
mkdir SiPixelTools
git clone https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration.git
mv SiPixelTools-LA-Calibration SiPixelTools/LA-Calibration
scram b -j
```
leads to 
```
--- Registered EDM Plugin: SiPixelLorentzAngleTest
/afs/cern.ch/work/t/tvami/public/TemplateProduction/inputTrees/CMSSW_11_3_4_patch1/src/SiPixelTools/LA-Calibration/src/SiPixelLorentzAngle.cc:164:6: error: no declaration matches 'void SiPixelLorentzAngle::beginRun(const edm::Run&, const edm::EventSetup&)'
  164 | void SiPixelLorentzAngle::beginRun(const edm::Run & iRun, const edm::EventSetup & es){
      |      ^~~~~~~~~~~~~~~~~~~
/afs/cern.ch/work/t/tvami/public/TemplateProduction/inputTrees/CMSSW_11_3_4_patch1/src/SiPixelTools/LA-Calibration/src/SiPixelLorentzAngle.cc:164:6: note: no functions named 'void SiPixelLorentzAngle::beginRun(const edm::Run&, const edm::EventSetup&)'
In file included from /afs/cern.ch/work/t/tvami/public/TemplateProduction/inputTrees/CMSSW_11_3_4_patch1/src/SiPixelTools/LA-Calibration/src/SiPixelLorentzAngle.cc:32:
/afs/cern.ch/work/t/tvami/public/TemplateProduction/inputTrees/CMSSW_11_3_4_patch1/src/SiPixelTools/LA-Calibration/src/../interface/SiPixelLorentzAngle.h:86:7:note: 'class SiPixelLorentzAngle' defined here
   86 | class SiPixelLorentzAngle : public edm::EDAnalyzer
      |       ^~~~~~~~~~~~~~~~~~~
gmake: *** [config/SCRAM/GMake/Makefile.rules:1694: tmp/slc7_amd64_gcc900/src/SiPixelTools/LA-Calibration/src/SiPixelToolsLA-Calibration/SiPixelLorentzAngle.cc.o] Error 1
gmake: *** Waiting for unfinished jobs....
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```

@wweiphy can you have a look at it?
cc @tsusa @ferencek @OzAmram

**Comment by ferencek** [comment]
For me also the default instructions in https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration/blob/master/README.md are failing with
```
/users/ferencek/PixelOffline/SiPixelTools/CMSSW_11_2_0_pre10/src/SiPixelTools/LA-Calibration/src/SiPixelLorentzAngle.cc:33:10: fatal error: Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h: No such file or directory
 #include "Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/users/ferencek/PixelOffline/SiPixelTools/CMSSW_11_2_0_pre10/src/SiPixelTools/LA-Calibration/src/SiPixelLorentzAngle.cc:33:10: fatal error: Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h: No such file or directory
 #include "Geometry/TrackerGeometryBuilder/interface/PixelTopologyMap.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake: *** [config/SCRAM/GMake/Makefile.rules:1687: tmp/slc7_amd64_gcc820/src/SiPixelTools/LA-Calibration/src/SiPixelToolsLA-Calibration/SiPixelLorentzAngle.cc.o] Error 1
gmake: *** Waiting for unfinished jobs....
Leaving library rule at src/SiPixelTools/LA-Calibration/test
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```
So some investigation and possibly new branches are needed.

**Comment by tvami** [comment]
> So some investigation and possibly new branches are needed.

Just for the record (as you already know my opinion), if it was in central CMSSW then wouldn't be a need for new branches :P :) 
Of course this is more relevant for the other code, this specifically is planned to be included in CMSSW for the PCL anyway, IIUC.

**Comment by ferencek** [comment]
@tvami, I fixed the code and you can find an updated recipe at https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration

I understand your point about CMSSW but nothing comes completely for free. Even with the code in the CMSSW repository, there would be multiple instances of the same package living on different CMSSW branches and keeping all those up to date would generate some work. At the very least, the README file would have to be kept up to date.

In fact, the README file we had right before this fix had a broken recipe which worked with neither CMSSW_11_2_X nor CMSSW_11_3_X but the compilation was failing for different reasons in the two release cycles (I actually now wonder how were the latest code additions even tested).

This also made me realize that using the `master` branch and `git clone` without specifying the branch name is not such a great idea. Whenever a switch to a newer release cycle occurs, the old recipes potentially become broken. To be more explicit, the following recipe is future-proof
```
cmsrel CMSSW_11_2_0
cd CMSSW_11_2_0/src/
cmsenv
git clone -b CMSSW_11_2_X https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration.git SiPixelTools/LA-Calibration
```
while
```
cmsrel CMSSW_11_2_0
cd CMSSW_11_2_0/src/
cmsenv
git clone https://github.com/CMSTrackerDPG/SiPixelTools-LA-Calibration.git SiPixelTools/LA-Calibration
```
isn't.

**Comment by wweiphy** [comment]
Thanks @ferencek 

@tvami I also noticed that this version of code does not have bowing correction and surface deformation for LA fitting.
It does not affect the Tree production but do you want me add those in?

**Comment by tvami** [comment]
Hi @wweiphy I leave this to the conveners. For my purposes (trees for Morris) this is fine as it is (he'll do the corrections)

**Comment by tvami** [comment]
I understand that @ferencek fixed this, so I'm closing this issue
